@startuml createUserSSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor Admin as admin
participant EletricGO as system <<System(C4)>>


admin -> system: I want to create a new User
activate system

system --> admin: asks for the details on the new User
deactivate system

admin -> system: inserts the information about the new User
activate system

system --> admin: informs about the success of the operation
deactivate system


deactivate system
deactivate admin

@enduml