@startuml deleteUserAdminSSD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor Admin as admin
participant EletricGO as system <<System(C4)>>


admin -> system: I want to delete a User
activate system

system --> admin: displays a list of users
deactivate system

admin -> system: selects the desired user and clicks on the delete button
activate system

system --> admin: informs about the successful deletion

deactivate system
deactivate admin

@enduml