@startuml createDeliverySD
autonumber

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

actor "Warehouse Manager" as admin


box "<<System(C4)>>\n       EletricGo" #LightYellow
participant SPA as ui <<Container(C4)>>
box "<<Container(C4)>>\nWarehouse Management" #LightGreen
participant DeliveryController as  CTL <<Component(C4)>>
participant DeliveryService as  SV <<Component(C4)>>
participant "Delivery : Delivery" as  delivery <<Component(C4)>>
participant "DeliveryDTO : DeliveryDTO" as  DTO <<Component(C4)>>
participant DeliveryRepository as  DR <<Component(C4)>>
end box
end box

admin -> ui: I want to create a new Delivery
activate ui

ui --> admin: asks for the details on the new Delivery
deactivate ui

admin -> ui: inserts the information about the new Delivery

activate ui

alt If the Delivery doesn't exist in the system 
ui -> CTL: POST Post(DeliveryDto)
activate CTL
CTL -> SV : CreateDelivery(DeliveryDto)
activate SV

SV -> delivery : Create(DeliveryDto)
activate delivery
delivery --> SV : Delivery 
deactivate delivery

SV -> DR : save(Delivery)
activate DR
DR --> SV : true 
deactivate DR

SV -> delivery : toDeliveryDTO()
activate delivery
delivery --> SV : DeliveryDto
deactivate delivery
SV --> CTL : DeliveryDto
deactivate SV
CTL --> ui : DeliveryDto

CTL --> ui: 200 OK
deactivate CTL


ui --> admin: informs about the success of the operation



else If a Delivery already exists with the id entered




CTL -> SV : CreateDelivery(DeliveryDto)
activate CTL
activate SV

SV -> delivery : Create(DeliveryDto)
activate delivery
delivery --> SV : Delivery 
deactivate delivery

SV -> DR : save(Delivery)
activate DR
DR --> SV : false
deactivate DR
SV --> CTL : BadRequestException
deactivate SV
CTL --> ui : BadRequestException


CTL --> ui: 400 BAD REQUEST
deactivate CTL


ui --> admin: informs about the fail of the operation


else If the attributes do not respect the business rules


CTL -> SV : CreateDelivery(DeliveryDto)
activate CTL
activate SV

SV -> delivery : Create(DeliveryDto)
activate delivery
delivery --> SV : BusinessRuleValidationException
deactivate delivery

SV --> CTL : BusinessRuleValidationException
deactivate SV
CTL --> ui : BusinessRuleValidationException

CTL --> ui: 400 BAD REQUEST
deactivate CTL
ui --> admin: informs about the fail of the operation

deactivate ui
end 
deactivate admin

@enduml
