// <auto-generated />
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20221105184053_InitialCreat")]
    partial class InitialCreat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DDDNetCore.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("DDDSample1.Domain.Delivery.Delivery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Warehouses.Warehouse", b =>
                {
                    b.OwnsOne("DDDNetCore.Domain.Warehouses.Altitude", "Altitude", b1 =>
                        {
                            b1.Property<string>("WarehouseId")
                                .HasColumnType("varchar(255)");

                            b1.Property<float>("AltitudeValue")
                                .HasColumnType("float");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Warehouses.WarehouseId", "WarehouseIdentifier", b1 =>
                        {
                            b1.Property<string>("WarehouseId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("WarehouseIdentifier")
                                .HasColumnType("longtext");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("DDDNetCore.Domain.Warehouses.WarehouseAddress", "WarehouseAddress", b1 =>
                        {
                            b1.Property<string>("WarehouseId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Country")
                                .HasColumnType("longtext");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .HasColumnType("longtext");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("DDDNetCore.Domain.Warehouses.WarehouseCoordinates", "WarehouseCoordinates", b1 =>
                        {
                            b1.Property<string>("WarehouseId")
                                .HasColumnType("varchar(255)");

                            b1.Property<float>("Latitude")
                                .HasColumnType("float");

                            b1.Property<float>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("DDDNetCore.Domain.Warehouses.WarehouseDesignation", "WarehouseDesignation", b1 =>
                        {
                            b1.Property<string>("WarehouseId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Text")
                                .HasColumnType("longtext");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("Altitude");

                    b.Navigation("WarehouseAddress");

                    b.Navigation("WarehouseCoordinates");

                    b.Navigation("WarehouseDesignation");

                    b.Navigation("WarehouseIdentifier");
                });

            modelBuilder.Entity("DDDSample1.Domain.Delivery.Delivery", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Warehouses.WarehouseId", "WarehouseId", b1 =>
                        {
                            b1.Property<string>("DeliveryId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("WarehouseIdentifier")
                                .HasColumnType("longtext");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Delivery.DeliveryDate", "DeliveryDate", b1 =>
                        {
                            b1.Property<string>("DeliveryId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<string>("Month")
                                .HasColumnType("longtext");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Delivery.DeliveryId", "DeliveryId", b1 =>
                        {
                            b1.Property<string>("DeliveryId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("DeliveryIdentifier")
                                .HasColumnType("longtext");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Delivery.DeliveryMass", "DeliveryMass", b1 =>
                        {
                            b1.Property<string>("DeliveryId")
                                .HasColumnType("varchar(255)");

                            b1.Property<float>("Mass")
                                .HasColumnType("float");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Delivery.DeliveryTime", "DeliveryTime", b1 =>
                        {
                            b1.Property<string>("DeliveryId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("placingTime")
                                .HasColumnType("int");

                            b1.Property<int>("withdrawalTime")
                                .HasColumnType("int");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.Navigation("DeliveryDate");

                    b.Navigation("DeliveryId");

                    b.Navigation("DeliveryMass");

                    b.Navigation("DeliveryTime");

                    b.Navigation("WarehouseId");
                });
#pragma warning restore 612, 618
        }
    }
}
